### ISSUE TITLE
Refactor AccountInterface & BlockInterface in EVM

### ISSUE THREAD

**Issue by vyorkin** [mana-ethereum/mana#114]
We need to refactor mock_interface & block_interface, otherwise its quiet hard to understand whats wrong with evm tests. One issue is that it includes `caller` account as well, which needs to be ignored when comparing to the expected accounts state (those listed in `"post"` in the corresponding json file).
I suggest to use the `mox` for mocking instead

**Comment by hayesgm** [comment]
This was addressed in #494
