### ISSUE TITLE
I want to be able to run a command line application so I can see my mana application running.

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#3]
Currently the only way to actually run Exthereum is through ‘iex -S mix’ in tests. To start we should  create a CLI application that runs the following code:

https://github.com/exthereum/blockchain/blob/master/test/ropsten_test.exs#L14-L35

**Comment by hayesgm** [comment]
This is addressed by #548, though there's still a long way to go (e.g. hosting an RPC server and running DevP2P)
