### ISSUE TITLE
`mix run --no-halt` should sync the blockchain

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#399]
Running `mix run --no-halt` with `sync` set to `true` should pull block bodies one by one.

Currently setting `sync` to `true` in [ex_wire/config/dev.exs](https://github.com/poanetwork/mana/blob/master/apps/ex_wire/config/dev.exs)

and running `mix run --no-halt` I get the following output:

````
12:03:04.005 [debug] [Network] [633279...6b0b0f] Established outbound connection with 52.232.243.152.

12:03:04.065 [debug] [Network] [633279...6b0b0f] Sending raw data message of length 388 byte(s) to 52.232.243.152

12:03:04.127 [debug] [Network] [94c15d...c35f09] Established outbound connection with 192.81.208.223.

12:03:04.130 [debug] [Network] [94c15d...c35f09] Sending raw data message of length 388 byte(s) to 192.81.208.223

12:03:04.703 [warn]  [Network] [633279...6b0b0f] Failed to get handshake message when expecting ack - Invalid ECIES encoded message

12:03:04.744 [warn]  [Network] [633279...6b0b0f] Failed to get handshake message when expecting ack - Invalid ECIES encoded message

12:03:05.360 [warn]  [Network] [94c15d...c35f09] Failed to get handshake message when expecting ack - Invalid ECIES encoded message

12:03:05.360 [warn]  [Network] [94c15d...c35f09] Peer closed connection
````

Ideally we would connect to some nodes and query for blocks one by one like in the sync task we build on [this branch](https://github.com/poanetwork/mana/compare/masonforest/blockchain-sync-mix-task).

**Comment by germsvel** [comment]
@masonforest I'm not sure if these things are helpful or not, but be sure to set your private key in the config file before you run `mix run --no-halt`. Otherwise, it generates a random one every time you need one. 

My guess is that that might help you get past the encrypted handshake issue there since it's probably using one key to encrypt the handshake and another one to read the handshake sent by the peer.

**Comment by masonforest** [comment]
I tried copying the private key from `apps/ex_wire/config/test.exs` into `apps/ex_wire/config/dev.exs` (`<<10, 122.., 30>>`)

Looks like that fixed the `Invalid ECIES encoded message` error but I still get:

````
15:23:48.331 [debug] [Network] [633279...6b0b0f] Established outbound connection with 52.232.243.152.

15:23:48.393 [debug] [Network] [633279...6b0b0f] Sending raw data message of length 388 byte(s) to 52.232.243.152

15:23:48.422 [debug] [Network] [94c15d...c35f09] Established outbound connection with 192.81.208.223.

15:23:48.425 [debug] [Network] [94c15d...c35f09] Sending raw data message of length 388 byte(s) to 192.81.208.223

15:23:50.350 [warn]  [Network] [94c15d...c35f09] Peer closed connection

15:24:17.578 [warn]  [Network] [633279...6b0b0f] Peer closed connection
````

**Comment by hayesgm** [comment]
Plenty of work to do, but I don't believe that `mix run --no-halt` should actually run p2p connections. The new system will incorporate syncing as well as behaving well as part of a bigger application. As such, closing this issue now.
