### ISSUE TITLE
Implement RLPx Flow Control

### ISSUE THREAD

**Issue by germsvel** [mana-ethereum/mana#408]
RLPx specifies the implementation for [flow control](https://github.com/ethereum/devp2p/blob/master/rlpx.md#flow-control). 

There is a note in there, however, that states the following: 
> Note: The initial version of RLPx will set a static window-size of 8KB; fair queueing and flow control (DeltaUpdate packet) will not be implemented.

So it is uncertain whether or not that needs to be implemented on first pass. A quick looking at parity, however, makes it seem that it does implement the flow control. See, for example, the mention of `flow_params` in [net/status.rs](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/light/src/net/status.rs).

**Comment by hayesgm** [comment]
This has been removed from the RLPx specification.
