### ISSUE TITLE
fix `libsecp256k1` compilation

### ISSUE THREAD

**Issue by ayrat555** [mana-ethereum/mana#415]
Currently, we are manually compiling `libsecp256k1` in setup script https://github.com/poanetwork/mana/blob/master/bin/setup#L114

Potential solutions:
- Port required functionality to Elixir - https://github.com/ethereum/py_ecc/blob/master/py_ecc/secp256k1/secp256k1.py
- Fix make file of  `libsecp256k1` nif - https://github.com/exthereum/libsecp256k1/blob/master/Makefile

See also https://github.com/poanetwork/mana/pull/413

**Comment by Lokraan** [comment]
What do you think about coding the functionality in rust, and then porting it to elixir via rustler?

**Comment by ayrat555** [comment]
@Lokraan I think that's a possible solution.

**Comment by Lokraan** [comment]
@ayrat555 I'll start working on that then.

**Comment by ayrat555** [comment]
it's ok with me 
cc @masonforest @germsvel

**Comment by igorbarinov** [comment]
> @ayrat555 I'll start working on that then.

@Lokraan are you sure? IMO it's very ambitious and time-consuming task to do

**Comment by Lokraan** [comment]
@igorbarinov The code is already out there, I just have to port it to rust syntax.

**Comment by igorbarinov** [comment]
@Lokraan do you plan to use https://github.com/ETCDEVTeam/libsecp256k1-rs ?

**Comment by Lokraan** [comment]
@igorbarinov I can use that, I was planning on writing it manually.

**Comment by hayesgm** [comment]
Have you tried building with version [https://hex.pm/packages/libsecp256k1/0.1.10](0.1.10)? It should generally fix compilation issues.

**Comment by hayesgm** [comment]
Marking as done with the upgrade to 0.1.10
