### ISSUE TITLE
We're not running all the evm tests

### ISSUE THREAD

**Issue by MattMSumner** [mana-ethereum/mana#434]

**Comment by MattMSumner** [comment]
This could lead to a regression. We're not running them all since it will time out CI. I think we could resolve this by parallelizing the tests.

**Comment by hayesgm** [comment]
Which tests are not being run? Can we verify if/if not this is still true?

**Comment by MattMSumner** [comment]
It looks like like some of the "performance" tests are being skipped: https://github.com/mana-ethereum/mana/blob/master/apps/evm/test/evm_test.exs#L19-L40

**Comment by hayesgm** [comment]
In that case, let's close this issue in lieu of #565 to run those tests
