### ISSUE TITLE
Fix `create2collisionStorage` blockchain test in Constantinople

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#442]
It looks like this test starts with an account with storage set and overwrites that address with a contract. It's unclear how storage could be set without first setting an account's contract code. We can either tweak our logic [here](https://github.com/poanetwork/mana/pull/439/files#diff-edac525fc04ad2ad9ae55d8b2f111b2fR56) or ask the [Ethereum testing gitter](https://gitter.im/ethereum/tests).

**Comment by hayesgm** [comment]
@masonforest Was this issue fixed by #439 ?

**Comment by masonforest** [comment]
Yep! Closing... Thanks for cleaning these up!
