### ISSUE TITLE
Convert  SyncWithInfura into a mix task

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#453]
Currently `SyncWithInfura` is [a script](https://github.com/poanetwork/mana/blob/master/apps/blockchain/scripts/sync_with_infura.ex).

We should convert it to a mix task like `Sync.ToFile` so we get the mix documentation that comes with that.

**Comment by bradleystachurski** [comment]
I'm happy to give this a go!

**Comment by hayesgm** [comment]
This is implemented in #548
