### ISSUE TITLE
Precompute valid JUMP destinations

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#560]
Before calling the JUMP opcode we call [`valid_jump_dest?`](https://github.com/mana-ethereum/mana/blob/d0fa75ce5646a85fd925de7e30c63a838b183517/apps/evm/lib/evm/machine_code.ex#L57) to see if the jump destination is valid. Currently we compute `valid_jump_destinations` every time JUMP is called. This value should be precomputed and saved. If we want to make this even faster we can store valid destinations in a  bitmap like [Geth did](https://github.com/ethereum/go-ethereum/pull/14570/files).

Here's a article about [an attack](https://www.ethnews.com/mainnet-attacked-fix-swiftly-supplied) on this vulnerability and how Geth fixed it.

**Comment by hayesgm** [comment]
Marking this as medium, but from what you're saying, maybe this is a high-priority issue to speed up transaction processing?

**Comment by masonforest** [comment]
Yeah, I don't know exactly how much this could speed things up but if it really is running through the whole contract every time we hit a JUMP that seems like that could be significant. I changed the priority to high and I'll get to this this week!
