### ISSUE TITLE
Dialyzer issues

### ISSUE THREAD

**Issue by InoMurko** [mana-ethereum/mana#562]
We should start by removing the content of .dialyzer.ignore-warnings.
Any special dialyzer issues should be addressed case by case and decided what to do.

**Comment by ayrat555** [comment]
Also, we can stop using dialyzer because it may not give us any value. But it takes quite some time to fix dialyzer errors every time

**Comment by InoMurko** [comment]
Can you elaborate what you mean?

**Comment by ayrat555** [comment]
Dialyzer errors are very cryptic and sometimes it hard to understand what exactly wrong with typespecs.

**Comment by InoMurko** [comment]
Oh yeah, you're right! Dialyzer is difficult. But the prize at the end is awesome :)
I think it's better for us if we stick to dialyzer, help each other (ping me anytime) and fix the errors. There's a couple of things we get from Dialyzer that are very meaningful for a successful project, like
- code becomes a lot safer
- you find bugs
- it reduces code complexity and increases code maintainability, readability 
- on boarding new resources is quicker - they can start contributing sooner
- if you decide to ignore it now, and are forced to add it later - you're in no good 🔥

**Comment by hayesgm** [comment]
I'd also add (or repeat): typespecs serve as documentation. When I read erlang/Elixir docs, I spend more time reading the typespec than the docs themselves, since it clears up exactly what the inputs and outputs are. I agree we should fix as many Dialyzer warnings as possible.

@InoMurko Serious question: do you think it's possible to fix all warnings? In my experience, sometimes Dialyzer has bugs, or your downstream libraries have incorrect specs and you're forced to just ignore the issue and move on. Have you had the same experiences?

**Comment by InoMurko** [comment]
My experience is that you can't fix all warnings, mostly those coming from dependencies you're not willing to fix yourself (but Mana is very dependency light) and also If you start late it gets increasingly difficult. If you use dialyzer from day 1 it forces you to write code you fully understand. Which is awesome!
I have never encountered a Dialyzer bug though. You can analyse the whole OTP and it comes out clean. Not saying it's not possible.

**Comment by hayesgm** [comment]
Ino-- I have a large number of changes coming to ExWire, which specifically adds and cleans up a large number of typespecs. We might end up with a pretty large conflict, so maybe hold off until that PR is up?

**Comment by InoMurko** [comment]
Ok! There are three apps that don't go through dialyzer. abi, exth_crypto and ex_wire. I'll do exth_crypto then.

**Comment by InoMurko** [comment]
I think as of now, this is no longer relevant. Issues that could be addressed have been solved in many PR's. Closing.
