### ISSUE TITLE
Block header improvements

### ISSUE THREAD

**Issue by vyorkin** [mana-ethereum/mana#62]
- [x] Refactor validation (maybe extract `Validator`'s for each eq. that implement `validate(header)`) - done as part of #178
- [ ] Add POW check to the block header validation

by PoW check I mean
![image](https://user-images.githubusercontent.com/988849/39992573-e72bc768-577b-11e8-9d1a-24c3cea663d9.png)

Maybe:

* Add tests for setting homestead_block
* Add tests for setting initial_difficulty
* Add tests for setting minimum_difficulty
* Add tests for setting difficulty_bound_divisor
* Add tests for setting gas_limit_bound_divisor
* Add tests for setting min_gas_limit

**Comment by hayesgm** [comment]
Closing in lieu of #541
