### ISSUE TITLE
Syncing with Kovan (42) and Rinkeby (4)

### ISSUE THREAD

**Issue by InoMurko** [mana-ethereum/mana#630]
We also need to come to an agreement of consistent ids of chains per https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version

wdyt @hayesgm ?

**Comment by InoMurko** [comment]
Added by @hayesgm in #671

**Comment by hayesgm** [comment]
They come in the json files that are shipped with Parity, so I think we're good on that @InoMurko
