### ISSUE TITLE
Allow efficient Block lookup by block number

### ISSUE THREAD

**Issue by willmeister** [mana-ethereum/mana#653]
Given a `Trie`, we can look up a `Block` by block hash, but we cannot efficiently look up a block by number. As a workaround, we have things like `Blockchain.BlockHeaderInfo.get_ancestor_header(...)` that loops through getting the parent hash and looking up the parent by the hash until we get the block with the desired number.

This issue is to add block number => block storage and efficient lookups.

**Comment by hayesgm** [comment]
Makes sense. Do we have / should we add a generic KV store for these types of items? This is effectively just an index that tracks the best block at a given height to a block hash?
