### ISSUE TITLE
Process queued blocks when Syncing to another node

### ISSUE THREAD

**Issue by germsvel** [mana-ethereum/mana#75]
Currently, we are syncing information to other blocks (satisfying some of the [eth wire protocol](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#basic-chain-syncing)) in `lib/ex_wire/sync.ex`. 

That GenServer currently requests `BlockHeaders` and `BlockBodies` but it only stores them in a `BlockQueue` because we want to ensure the blocks are confirmed by several peers (just how many peers need to confirm that is available for configuration in `ex_wire` app's config). 

What we need to do now is process all of the blocks in the `BlockQueue` that have been confirmed by multiple peers. We need to validate them and add them to our chain.

**Comment by hayesgm** [comment]
This is now completed in our ExWire sync.
