### ISSUE TITLE
Use ets tables as storage for node discovery

### ISSUE THREAD

**Issue by ayrat555** [mana-ethereum/mana#89]
Currently we store all nodes and buckets in memory.

https://github.com/poanetwork/mana/blob/master/apps/ex_wire/lib/ex_wire/kademlia/server.ex#L25

We should consider using ets tables for storing them

**Comment by hayesgm** [comment]
I believe a GenServer, as it exists, should be sufficient. Not sure what ets offers us over the current solution.
