### ISSUE TITLE
Trie never deletes nodes from the DB

### ISSUE THREAD

**Issue by vyorkin** [mana-ethereum/mana#93]
This is #69 follow up.

Here is the related PR in Parity: https://github.com/paritytech/parity/pull/1408#issuecomment-228401955, as I understand they've had the same issue in the past.

We need to review the MMPT implementation in Parity, especially the places related to `death_row`:
https://github.com/paritytech/parity/blob/a04c5b180a821c709b0ea24c7d4f21c9c2511839/util/patricia_trie/src/triedbmut.rs#L369
https://github.com/paritytech/parity/blob/a04c5b180a821c709b0ea24c7d4f21c9c2511839/util/patricia_trie/src/triedbmut.rs#L821

**Comment by vyorkin** [comment]
related discussion in Slack: https://poanetwork.slack.com/archives/GA89BNBT7/p1528708936000135?thread_ts=1526994549.000595&cid=GA89BNBT7

**Comment by hayesgm** [comment]
For the time being, I suppose we should just be an "archive node." We can come back to this once the node is fully functioning. Thanks for investigating.
