### ISSUE TITLE
Handle multi-frame packets in ExWire

### ISSUE THREAD

**Issue by germsvel** [mana-ethereum/mana#97]
The [RLPx specification](https://github.com/ethereum/devp2p/blob/master/rlpx.md#framing) says, 

> A multi-frame packet is a packet which is split (aka chunked) into multiple frames because it's size is larger than the protocol window size

Currently, the `Frame` module only handles a single or _normal_ frame. At some point we need to handle multi-frame packets. 

There is also a `TODO` comment in `lib/ex_wire/framing/frame.ex` to that effect.

**Comment by hayesgm** [comment]
Chunked framing has since been removed from the spec. Do we do cover a single frame being split over multiple packets, however, and this is fixedin #569.
